MOC: Change to 2.4.4; fixes issue with ltdl library
Version 2.4.3 would give lots of complaints compiling ltdl.c, for instance

ltdl.c:863:31: error: 'LTDL_OBJDIR' undeclared here (not in a function)

Also changed to Source forge mirror