classes/native*.bbclass: fix error during parse with bitbake master
Fixes "AttributeError: 'NoneType' object has no attribute 'split'" during
parsing with bitbake master. We should not be calling explode_deps with
None as the argument, so ensure the value isn't None.

Signed-off-by: Paul Eggleton <paul.eggleton@linux.intel.com>
Acked-by: Andrea Adami <andrea.adami@gmail.com>
(cherry picked from commit 6f3334a9a1ef5953a0a9e2b6ec92705a3f9295d1)